/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param id 
 */


data class CompanyDto (

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("id")
    val id: java.util.UUID

) {


}

