/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.LoanType

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param amount 
 * @param interest 
 * @param numberDate 
 * @param loanType 
 * @param borrowerClientId 
 * @param suggestedDays 
 */


data class CreateLoanDto (

    @SerializedName("amount")
    val amount: kotlin.Double,

    @SerializedName("interest")
    val interest: kotlin.Double,

    @SerializedName("numberDate")
    val numberDate: kotlin.Int,

    @SerializedName("loanType")
    val loanType: LoanType,

    @SerializedName("borrowerClientId")
    val borrowerClientId: java.util.UUID,

    @SerializedName("suggestedDays")
    val suggestedDays: kotlin.collections.List<kotlin.String>? = null

) {


}

