/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.CreatePersonDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param displayName 
 * @param companyId 
 * @param createPersonDto 
 */


data class CreateBorrower (

    @SerializedName("displayName")
    val displayName: kotlin.String,

    @SerializedName("companyId")
    val companyId: java.util.UUID,

    @SerializedName("createPersonDto")
    val createPersonDto: CreatePersonDto

) {


}

