/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.LoanType
import org.confia.loanprintinvoice.models.SimplePayments

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param borrowerClientId 
 * @param amount 
 * @param interest 
 * @param dateTime 
 * @param numberDate 
 * @param loanType 
 * @param totalPayment 
 * @param totalAmount 
 * @param payments 
 * @param progressPercentage 
 * @param status 
 */


data class LoanDtoAndPayments (

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("borrowerClientId")
    val borrowerClientId: java.util.UUID,

    @SerializedName("amount")
    val amount: kotlin.Double,

    @SerializedName("interest")
    val interest: kotlin.Double,

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime,

    @SerializedName("numberDate")
    val numberDate: kotlin.Int,

    @SerializedName("loanType")
    val loanType: LoanType,

    @SerializedName("totalPayment")
    val totalPayment: kotlin.Double,

    @SerializedName("totalAmount")
    val totalAmount: kotlin.Double,

    @SerializedName("payments")
    val payments: kotlin.collections.List<SimplePayments>,

    @SerializedName("progressPercentage")
    val progressPercentage: kotlin.Double,

    @SerializedName("status")
    val status: kotlin.String? = null

) {


}

