/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.PointDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param loanId 
 * @param amount 
 * @param isYape 
 * @param location 
 */


data class NewPaymentDto (

    @SerializedName("loanId")
    val loanId: java.util.UUID,

    @SerializedName("amount")
    val amount: kotlin.Double,

    @SerializedName("isYape")
    val isYape: kotlin.Boolean,

    @SerializedName("location")
    val location: PointDto? = null

) {


}

