/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.PointDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param dateTime 
 * @param amount 
 * @param location 
 * @param isYape 
 * @param number 
 * @param loanId 
 */


data class PaymentDto (

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime,

    @SerializedName("amount")
    val amount: kotlin.Double,

    @SerializedName("location")
    val location: PointDto,

    @SerializedName("isYape")
    val isYape: kotlin.Boolean,

    @SerializedName("number")
    val number: kotlin.Int,

    @SerializedName("loanId")
    val loanId: java.util.UUID

) {


}

