/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.BorrowerClientDtoWithActiveLoans

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param borrowerClientDtoWithActiveLoans 
 * @param paymentId 
 */


data class PaymentResponseDto (

    @SerializedName("borrowerClientDtoWithActiveLoans")
    val borrowerClientDtoWithActiveLoans: BorrowerClientDtoWithActiveLoans,

    @SerializedName("paymentId")
    val paymentId: java.util.UUID

) {


}

