/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param dni 
 * @param phoneNumber 
 * @param id 
 * @param birthday 
 * @param address 
 * @param notes 
 */


data class PersonDto (

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("dni")
    val dni: kotlin.String,

    @SerializedName("phoneNumber")
    val phoneNumber: kotlin.String,

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("birthday")
    val birthday: java.time.OffsetDateTime? = null,

    @SerializedName("address")
    val address: kotlin.String? = null,

    @SerializedName("notes")
    val notes: kotlin.String? = null

) {


}

