/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.ReportPaymentsDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param dateTime 
 * @param totalPayment 
 * @param detailsDto 
 */


data class ReportPaymentByDayDto (

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime,

    @SerializedName("totalPayment")
    val totalPayment: kotlin.Double,

    @SerializedName("detailsDto")
    val detailsDto: kotlin.collections.List<ReportPaymentsDto>

) {


}

