/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.CompanyDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param changeBy 
 * @param name 
 * @param company 
 * @param displayName 
 * @param loanDate 
 * @param amount 
 * @param payment 
 * @param isYape 
 */


data class ReportPaymentsDto (

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("changeBy")
    val changeBy: java.util.UUID,

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("company")
    val company: CompanyDto,

    @SerializedName("displayName")
    val displayName: kotlin.String,

    @SerializedName("loanDate")
    val loanDate: java.time.OffsetDateTime,

    @SerializedName("amount")
    val amount: kotlin.Double,

    @SerializedName("payment")
    val payment: kotlin.Double,

    @SerializedName("isYape")
    val isYape: kotlin.Boolean

) {


}

