/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.PermissionDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param name 
 * @param roles 
 * @param permissions 
 */


data class RoleDto (

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("roles")
    val roles: kotlin.collections.List<RoleDto>,

    @SerializedName("permissions")
    val permissions: kotlin.collections.List<PermissionDto>

) {


}

