/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param name 
 * @param rolesId 
 * @param permissionsId 
 * @param id 
 */


data class SaveRoleDto (

    @SerializedName("name")
    val name: kotlin.String,

    @SerializedName("rolesId")
    val rolesId: kotlin.collections.List<java.util.UUID>,

    @SerializedName("permissionsId")
    val permissionsId: kotlin.collections.List<kotlin.String>,

    @SerializedName("id")
    val id: java.util.UUID? = null

) {


}

