/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.CreatePersonDto
import org.confia.loanprintinvoice.models.UserToRegister

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param user 
 * @param createPersonDto 
 * @param rolesId 
 * @param permissionsId 
 * @param companyIds 
 */


data class SaveUserDto (

    @SerializedName("user")
    val user: UserToRegister,

    @SerializedName("createPersonDto")
    val createPersonDto: CreatePersonDto,

    @SerializedName("rolesId")
    val rolesId: kotlin.collections.List<java.util.UUID>,

    @SerializedName("permissionsId")
    val permissionsId: kotlin.collections.List<kotlin.String>,

    @SerializedName("companyIds")
    val companyIds: kotlin.collections.List<java.util.UUID>

) {


}

