/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param dateTime 
 * @param amount 
 * @param id 
 */


data class SimplePayments (

    @SerializedName("dateTime")
    val dateTime: java.time.OffsetDateTime,

    @SerializedName("amount")
    val amount: kotlin.Double,

    @SerializedName("id")
    val id: java.util.UUID? = null

) {


}

