/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models

import org.confia.loanprintinvoice.models.CompanyDto
import org.confia.loanprintinvoice.models.PermissionDto
import org.confia.loanprintinvoice.models.PersonDto
import org.confia.loanprintinvoice.models.RoleDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param email 
 * @param isActive 
 * @param person 
 * @param roles 
 * @param permissions 
 * @param companies 
 * @param avatar 
 * @param background 
 */


data class UserDto (

    @SerializedName("id")
    val id: java.util.UUID,

    @SerializedName("email")
    val email: kotlin.String,

    @SerializedName("isActive")
    val isActive: kotlin.Boolean,

    @SerializedName("person")
    val person: PersonDto,

    @SerializedName("roles")
    val roles: kotlin.collections.List<RoleDto>,

    @SerializedName("permissions")
    val permissions: kotlin.collections.List<PermissionDto>,

    @SerializedName("companies")
    val companies: kotlin.collections.List<CompanyDto>,

    @SerializedName("avatar")
    val avatar: kotlin.String? = null,

    @SerializedName("background")
    val background: kotlin.String? = null

) {


}

