/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.confia.loanprintinvoice.models


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param email 
 * @param isActive 
 * @param id 
 * @param password 
 * @param picture 
 */


data class UserToRegister (

    @SerializedName("email")
    val email: kotlin.String,

    @SerializedName("isActive")
    val isActive: kotlin.Boolean,

    @SerializedName("id")
    val id: java.util.UUID? = null,

    @SerializedName("password")
    val password: kotlin.String? = null,

    @SerializedName("picture")
    val picture: kotlin.String? = null

) {


}

